# Generated by Django 5.2.8 on 2025-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=("email", "role"), name="unique_email_role"
            ),
        ),
    ]
