# Generated by Django 5.2.8 on 2025-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0002_customuser_unique_email_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="resume_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
