# Generated by Django 5.2.8 on 2025-11-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0003_candidate_resume_link_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
