# Generated by Django 5.2.8 on 2025-11-19 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0004_alter_customuser_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyTests",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_title", models.TextField(blank=True, null=True)),
                ("test_is_timed", models.BooleanField(blank=True, null=True)),
                ("test_timer", models.TextField(blank=True, null=True)),
                ("test_questions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobVacancies",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.TextField(blank=True, null=True)),
                ("skills_required", models.TextField(blank=True, null=True)),
                ("level_of_experience", models.TextField(blank=True, null=True)),
                ("additional_requirements", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("timings", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestScores",
            fields=[
                ("score_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_marks", models.IntegerField(blank=True, null=True)),
                ("obtained_marks", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="customuser",
            name="unique_email_role",
        ),
        migrations.AddField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="companytests",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Backend.company"
            ),
        ),
        migrations.AddField(
            model_name="jobvacancies",
            name="candidates_applied",
            field=models.ManyToManyField(
                related_name="applied_jobs", to="Backend.candidate"
            ),
        ),
        migrations.AddField(
            model_name="jobvacancies",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Backend.company"
            ),
        ),
        migrations.AddField(
            model_name="companytests",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Backend.jobvacancies"
            ),
        ),
        migrations.AddField(
            model_name="testscores",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Backend.company"
            ),
        ),
        migrations.AddField(
            model_name="testscores",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Backend.jobvacancies"
            ),
        ),
        migrations.AddField(
            model_name="testscores",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Backend.companytests"
            ),
        ),
        migrations.AddField(
            model_name="testscores",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Backend.candidate"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobvacancies",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("job_title__isnull", True),
                        ("skills_required__isnull", True),
                        ("level_of_experience__isnull", True),
                        ("additional_requirements__isnull", True),
                        ("location__isnull", True),
                        ("timings__isnull", True),
                    ),
                    models.Q(
                        ("job_title__isnull", False),
                        ("skills_required__isnull", False),
                        ("level_of_experience__isnull", False),
                        ("additional_requirements__isnull", False),
                        ("location__isnull", False),
                        ("timings__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="job_fields_all_or_none",
            ),
        ),
        migrations.AddConstraint(
            model_name="companytests",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("test_is_timed", True), ("test_timer__isnull", False)),
                    models.Q(("test_is_timed", False), ("test_timer__isnull", True)),
                    _connector="OR",
                ),
                name="check_timer_requirement",
            ),
        ),
    ]
