# Generated by Django 5.2.8 on 2025-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0005_companytests_jobvacancies_testscores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobvacancies",
            name="candidates_applied",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="applied_jobs",
                to="Backend.candidate",
            ),
        ),
    ]
