# Generated by Django 5.2.8 on 2025-12-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0006_alter_jobvacancies_candidates_applied"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="companytests",
            name="check_timer_requirement",
        ),
        migrations.RemoveConstraint(
            model_name="jobvacancies",
            name="job_fields_all_or_none",
        ),
        migrations.RenameField(
            model_name="companytests",
            old_name="test_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="jobvacancies",
            old_name="job_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="testscores",
            old_name="user",
            new_name="candidate",
        ),
        migrations.RenameField(
            model_name="testscores",
            old_name="score_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="testscores",
            old_name="test",
            new_name="test_template",
        ),
        migrations.RemoveField(
            model_name="companytests",
            name="company",
        ),
        migrations.RemoveField(
            model_name="testscores",
            name="company",
        ),
        migrations.RemoveField(
            model_name="testscores",
            name="job",
        ),
        migrations.RemoveField(
            model_name="testscores",
            name="obtained_marks",
        ),
        migrations.RemoveField(
            model_name="testscores",
            name="total_marks",
        ),
        migrations.AddField(
            model_name="testscores",
            name="test_marks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testscores",
            name="test_scores",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skills",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="companytests",
            name="test_is_timed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="companytests",
            name="test_questions",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companytests",
            name="test_timer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companytests",
            name="test_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="jobvacancies",
            name="candidates_applied",
            field=models.ManyToManyField(
                related_name="applied_jobs", to="Backend.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="jobvacancies",
            name="job_title",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobvacancies",
            name="level_of_experience",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobvacancies",
            name="location",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobvacancies",
            name="skills_required",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobvacancies",
            name="timings",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="companytests",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("test_is_timed", True), ("test_timer__gt", 0)),
                    models.Q(("test_is_timed", False), ("test_timer__isnull", True)),
                    _connector="OR",
                ),
                name="check_timer_logic",
            ),
        ),
    ]
