# Generated by Django 5.2.8 on 2025-12-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0007_remove_companytests_check_timer_requirement_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="companytests",
            name="check_timer_logic",
        ),
        migrations.AlterField(
            model_name="companytests",
            name="test_timer",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="companytests",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("test_is_timed", True), ("test_timer__gt", 0)),
                    models.Q(("test_is_timed", False), ("test_timer__lte", 0)),
                    _connector="OR",
                ),
                name="check_timer_logic",
            ),
        ),
    ]
