# Generated by Django 5.2.8 on 2025-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0008_remove_companytests_check_timer_logic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="save_jobs",
            field=models.ManyToManyField(
                related_name="saved_jobs_by_candidates", to="Backend.jobvacancies"
            ),
        ),
    ]
