# Generated by Django 5.2.8 on 2025-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0009_candidate_save_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="save_jobs",
            field=models.ManyToManyField(
                related_name="saved_jobs", to="Backend.jobvacancies"
            ),
        ),
    ]
